import { DefaultTheme } from "styled-components";

export const lightTheme: DefaultTheme = {
	bodyTextColor: "#111",
	bodyBackgroundColor: "#fafafa",
	navBarHeight: "57",
	navBarTextColor: "#111",
	navBarHoverTextColor: "#e84142",
	navBarBackgroundColor: "#8a95bb",
	navBarBorderColor: "#555",
	mainTitleTextColor: "#111",
	linkHoverTextColor: "#e84142",
	sectionTitleTextColor01: "#111",
	sectionBackgroundColor01: "#e9ca6c",
	sectionBackgroundColor02: "#fafafa",
	sectionBorderStyle: "1px solid #111",
	lastUpdatedContainerTextColor: "#111",
	listTextColor: "#111",
	listBoxTextColor: "#111",
	listBoxHoverTextColor: "#e84142",
	listBoxBackgroundColor: "#f5f5f5",
	listBoxBorderStyle: "1px solid #111",
	nestedListDecoratorColor: "#e84142",
	tabBackgroundColor: "#8a95bb",
	tabActiveBackgroundColor: "#e84142",
};

export const darkTheme: DefaultTheme = {
	bodyTextColor: "#111",
	bodyBackgroundColor: "#111",
	navBarHeight: "57",
	navBarTextColor: "#ffe600",
	navBarHoverTextColor: "#d4ff00",
	navBarBackgroundColor: "#6d3c3c",
	navBarBorderColor: "#fff",
	mainTitleTextColor: "#ffe600",
	linkHoverTextColor: "#e84142",
	sectionTitleTextColor01: "#111",
	sectionBackgroundColor01: "#6e73a3",
	sectionBackgroundColor02: "#fafafa",
	sectionBorderStyle: "1px solid #111",
	lastUpdatedContainerTextColor: "#fff",
	listTextColor: "#111",
	listBoxTextColor: "#111",
	listBoxHoverTextColor: "#e84142",
	listBoxBackgroundColor: "#f5f5f5",
	listBoxBorderStyle: "1px solid #111",
	nestedListDecoratorColor: "#ffe600",
	tabBackgroundColor: "#6d3c3c",
	tabActiveBackgroundColor: "#e84142",
};
